spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  active:
    profile: dev
  application:
    name: RecycleRewards

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/recycleRewards?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}
bcrypt:
  strength: 10

security:
  basic:
    enabled: true
  ignored:
    - /static/**
    - /css/**
    - /js/**
    - /images/**
    - /favicon.ico
    - /error
  authorize-requests:
    - antMatchers("/admin/**").hasRole("ADMIN")
    - antMatchers("/client/**").hasRole("CLIENT")
    - antMatchers("/**").permitAll()
