spring:
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update

bcrypt:
  strength: 10

security:
  basic:
    enabled: true
  ignored:
    - /static/**
    - /css/**
    - /js/**
    - /images/**
    - /favicon.ico
    - /error

  providers:
    - user:
        name: admin
        password: ${ADMIN_PASSWORD:admin}
        authorities: ROLE_ADMIN

  passwords:
    encoding: bcrypt

authorize-requests:
  - antMatchers("/admin/**").hasRole("ADMIN")
  - antMatchers("/**").permitAll()