# spring.application.name=RecycleRewards
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  active:
    profile: dev
  application:
    name: RecycleRewards

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/recycleRewards?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true

  # Thymeleaf Configuration
  spring:
    thymeleaf:
      prefix: classpath:/templates/,classpath:/static/
      suffix: .html
      cache: false
      mode: HTML